[build]
command = "npm run build"
functions = "netlify/functions"
publish = "public"

[functions]
node_bundler = "esbuild"
# external_node_modules = ["sharp"]

[build.environment]
NODE_VERSION = "22"

[dev]
staticServerPort = 3998
port = 8887

[[redirects]]
from = "/api/v1/data"
to = "/.netlify/functions/fetch-all-data"
status = 200
force = true
